---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1.7"}

inputs:
- name: version
- name: git-phlow-tested
  trigger: true
outputs:
- name: project-bin

run:
  path: git-phlow/ci/scripts/create-binary.sh