resources:
    - name: git-phlow
      type: git
      source:
        uri: https://github.com/Praqma/git-phlow.git
        branch: develop
   
    - name: version
      type: semver
      source:
        driver: git
        uri: git@gituhb.com:praqma/git-phlow.git
        branch: version
        file: version
        private_key: {{concourse-repo-private-key}} 

jobs:
- name: integration-linux
  plan: 
  - get: git-phlow
    trigger: true
  - task: integration-test
    file: git-phlow/ci/tasks/test-linux.yml
  
- name: integration-darwin
  plan:
  - get: git-phlow
    trigger: true
  - task: integration-test-two
    file: git-phlow/ci/tasks/test-darwin.yml

- name: create-release-binary
  plan: 
    - get: version
    - get: git-phlow
    - task: create-release 
      file: git-phlow/ci/tasks/gen-bin.yml