resources:
    - name: git-phlow
      type: git
      source:
        uri: https://github.com/Praqma/git-phlow.git
        branch: develop
    
    - name: phlow-test-image
      type: docker-image
      source: 
        username: {{docker-hub-email}}
        password: {{docker-hub-password}}
        repository: {{docker-hub-url}}

jobs:
  - name: build-test-image
    plan:
    - get: git-phlow
      trigger: true
    #- get: phlow-test-image 
    - put: phlow-test-image
      params: 
        build: git-phlow
  - name: run-integration-tests
    plan: 
      - get: phlow-test-image
      - get: git-phlow
       # passed: [build-test-image]
      - task: run-tests
        file: git-phlow/ci/tasks/test.yml
  