resources:
    - name: git-phlow
      type: git
      source:
        uri: https://github.com/Praqma/git-phlow.git
        branch: master
    
    - name: test-image
      type: docker-image
      source: 
        email: {{docker-hub-email}}
        password: {{docker-hub-password}}
        repository: {{docker-hub-url}}

jobs:
  - name: integration
    plan:
    - get: git-phlow
      trigger: true
    - task: go-test
      file: git-phlow/ci/tasks/go_test.yml
