resources:
    - name: git-phlow
      type: git
      source:
        uri: https://github.com/Praqma/git-phlow.git
        branch: develop

jobs:
  - name: integration
    plan:
    - get: git-phlow
      trigger: true
    - task: go-test
      file: git-phlow/ci/tasks/go_test.yml
