resources: 
    - name: git-phlow-repo
      type: git
      source:
        uri: https://github.com/Praqma/git-phlow.git
        branch: master     

jobs: 
    - name: integration
      plan:
      - get: git-phlow-repo
        trigger: true
      - task: go-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: golang, tag: 1.7.4}  
          run:
            path: go
            args: [test]
